# Generated by Django 4.0.2 on 2022-02-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaoAPI', '0002_remove_user_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realname',
            field=models.CharField(default='realname', max_length=20),
            preserve_default=False,
        ),
    ]
